config/routes.rb
JournalDeBord::Application.routes.draw do
  resources :users

  get "home/index"

  resources :notes
  match 'home' => 'homet#index', :as => :home

  resources :projets

  get "pages/home"

  get "pages/contact"

  root :to => 'home#index'

end

app/models/projet.rb
class Projet < ActiveRecord::Base
  has_many :notes
  attr_accessible :id, :nom
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  # GET /projets
  # GET /projets.json
  def index
    @projets = Projet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projets }
    end
  end

  # GET /projets/1
  # GET /projets/1.json
  def show
    @projet = Projet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projet }
    end
  end

  # GET /projets/new
  # GET /projets/new.json
  def new
    @projet = Projet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projet }
    end
  end

  # GET /projets/1/edit
  def edit
    @projet = Projet.find(params[:id])
  end

  # POST /projets
  # POST /projets.json
  def create
    @projet = Projet.new(params[:projet])

    respond_to do |format|
      if @projet.save
        format.html { redirect_to @projet, notice: 'Projet was successfully created.' }
        format.json { render json: @projet, status: :created, location: @projet }
      else
        format.html { render action: "new" }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projets/1
  # PUT /projets/1.json
  def update
    @projet = Projet.find(params[:id])

    respond_to do |format|
      if @projet.update_attributes(params[:projet])
        format.html { redirect_to @projet, notice: 'Projet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projets/1
  # DELETE /projets/1.json
  def destroy
    @projet = Projet.find(params[:id])
    @projet.destroy

    respond_to do |format|
      format.html { redirect_to projets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/projets/_form.html.erb
<%= form_for(@projet) do |f| %>
  <% if @projet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projet.errors.count, "error") %> prohibited this projet from being saved:</h2>

      <ul>
      <% @projet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projets/edit.html.erb
<h1>Editing projet</h1>

<%= render 'form' %>

<%= link_to 'Show', @projet %> |
<%= link_to 'Back', projets_path %>

app/views/projets/index.html.erb
<h1>Listing projets</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projets.each do |projet| %>
  <tr>
    <td><%= projet.id %></td>
    <td><%= projet.nom %></td>
    <td><%= link_to 'Show', projet %></td>
    <td><%= link_to 'Edit', edit_projet_path(projet) %></td>
    <td><%= link_to 'Destroy', projet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Projet', new_projet_path %>

app/views/projets/new.html.erb
<h1>New projet</h1>

<%= render 'form' %>

<%= link_to 'Back', projets_path %>

app/views/projets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @projet.id %>
</p>

<p>
  <b>Nom:</b>
  <%= @projet.nom %>
</p>


<%= link_to 'Edit', edit_projet_path(@projet) %> |
<%= link_to 'Back', projets_path %>